pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven Project') {
            steps {
                script {
                    // Set up Maven environment
                    def mvnHome = tool 'Maven 3.9.6'
                    def mavenHome = mvnHome
                    def mavenCMD = "${mvnHome}/bin/mvn"
                    
                    // Run Maven build
                    sh "${mavenCMD} clean package"
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    // Build Docker image
                    docker.build("scriptsorcerer/comp367-webapp:${env.BUILD_NUMBER}")
                }
            }
        }

        stage('Docker Login') {
            steps {
                script {
                    // Login to Docker Hub
                    docker.withRegistry('https://registry.hub.docker.com', '1') {
                        // No need to do anything here, just logging in is enough
                    }
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    // Push Docker image to Docker Hub
                    docker.image("scriptsorcerer/comp367-webapp:${env.BUILD_NUMBER}").push()
                }
            }
        }
    }
}
