pipeline {
    agent any

    tools {
        maven '3.9.6'
        dockerTool 'docker'
    }
   

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/scriptsorcerer04/comp367-webapp']])
            }
        }
        
        stage('Build Maven Project') {
            steps {
                dir('comp367-webapp') {
                    bat 'mvn clean package'
                }
            }
        }
        
        stage('Docker Build') {
            steps {
                dir('comp367-webapp') {
                    script {
                        def dockerImage = docker.build("scriptsorcerer04/jenkins-comp367-webapp:${env.BUILD_NUMBER}")
        
                        dockerImage.tag("latest")
                      
                    }
                }
            }
        }
        
        stage('Docker Login') {
            steps {
                script {
                    
                    withCredentials([string(credentialsId: 'dockerhubpassword1', variable: 'dockerhubpassword')]) {
                        bat "docker login -u scriptsorcerer04 -p ${dockerhubpassword}"
                    }
                }
            }
        }
        stage ('Docker Push'){
            steps {
                script {
                    bat "docker push scriptsorcerer04/jenkins-comp367-webapp:latest"
                    
                }
            }
        }

    }
}